### ISSUE TITLE
How to limit the reveal area?

### ISSUE THREAD

**Issue by Stan92** [gloubibou/HHPanningTableViewCell#10]
Hello,
Thanks for sharing this code.. :)
Is it possible to leave a part of the cell "unrevealed" when you swipe the cell instead of having the entire cell revealed?
Thanks once again.

**Comment by gloubibou** [comment]
The stock version of HHPanningTableViewCell doesn't have that ability.

I believe there is a fork out there that added this.

**Comment by Stan92** [comment]
Thanks..I found it (from Neonkoala).
