### ISSUE TITLE
Incompatibility with SVPullToRefresh

### ISSUE THREAD

**Issue by gabro** [gloubibou/HHPanningTableViewCell#11]
Hi, I'm using this component along with [SVPullToRefresh](https://github.com/samvermette/SVPullToRefresh).

What happens is that after refreshing the tableview by pulling it, the cells are not swipable anymore, although the `drawerView` is present on every cell.

Any idea of why this is happening?

**Comment by gloubibou** [comment]
I have not yet used SVPullToRefresh.

Could you create a sample project showing the problem?
