### ISSUE TITLE
Brief "Flash" when sliding back to not revealed state

### ISSUE THREAD

**Issue by cohen72** [gloubibou/HHPanningTableViewCell#13]
Great Work!

I did a small customization to slide the cell only half way upon the "revealed" state. 

In doing so,  when I swipe the cell back to its "unrevealed" state, there is a very brief flash of the cell's view, probably because the subviews being added.

I cannot figure out how to prevent this "flash".  Any thoughts? 

Thanks!

**Comment by gloubibou** [comment]
Do you have a sample app?

Check for performSelector:withObject:afterDelay: and similar constructs.
The view is probably added an removed only at the next iteration or the run loop or at the completion of an animation.

**Comment by cohen72** [comment]
actually, I just made a hack to get around it - 

I added if (!self.drawerRevealed)  inside
- (void)gestureRecognizerDidPan:(UIPanGestureRecognizer*)gestureRecognizer 

as follows ...

if (state == UIGestureRecognizerStateBegan) {

```
    UIView *drawerView = self.drawerView;
    UIView *shadowView = self.shadowView;
    UIView *containerView = self.containerView;

    if (!self.drawerRevealed) {
        [self addSubview:drawerView];
        [self addSubview:shadowView];
        [self addSubview:containerView];
        [self setSelected:NO];
    }
    self.panOriginX = containerView.frame.origin.x;
    self.panning = NO;
}
```

**Comment by gloubibou** [comment]
Hi!

Your suggested changes leave the table cell transparent while dragging to close the drawer.

How does this work for you:

```
if (state == UIGestureRecognizerStateBegan) {
    UIView *drawerView = self.drawerView;
    UIView *shadowView = self.shadowView;
    UIView *containerView = self.containerView;

    if (self.drawerRevealed) {
        [self addSubview:containerView];
    }
    else {
        [self addSubview:drawerView];
        [self addSubview:shadowView];
    }

    [self setSelected:NO];

    self.panOriginX = containerView.frame.origin.x;
    self.panning = NO;
}
```

Best,
Pierre Bernard

**Comment by cohen72** [comment]
I tried this solution and for some reason it still flashes, but its much better!  Thank you for this suggestion :) By the way, I really love the work you did, great job!

**Comment by gloubibou** [comment]
Closing issue. Commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35 made major changes to HHPanningTableViewCell. This issue may not be current anymore.
