### ISSUE TITLE
Unknown UIView animation when closing "left swipe cell"

### ISSUE THREAD

**Issue by winograd** [gloubibou/HHPanningTableViewCell#17]
When I swipe back "left cell" there is a undetermined UIView animation in background. I didn't notice it until I set cell background to be transparent. It seams that shadowView is causing the problem but I can't determine why.

You can observe it you set HH_PANNING_ANIMATION_DURATION to 1.f and containerView alpha to .4 in createContainerView. Also colouring all the views makes it really easy to see.

I gave it a try to fix it, but had no luck. Maybe this problem is also causing the "Flash" from issue#13.

**Comment by gloubibou** [comment]
I made a small change that should suppress excessive animation of the shadow view.

**Comment by gloubibou** [comment]
Closing issue. Commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35 made major changes to HHPanningTableViewCell. This issue may not be current anymore.
