### ISSUE TITLE
UIStoryboards and reusing cells problem

### ISSUE THREAD

**Issue by vburojevic** [gloubibou/HHPanningTableViewCell#18]
I am using storyboards and dynamic cells, this line does not work because cells are never nil when using dynamic prototype cells and cell identifier, and therefore, HHPanningTableViewCell is not working.

With what should I replace these lines of code to make it work?

if (cell == nil) {
        cell = [[HHPanningTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault
                                              reuseIdentifier:CellIdentifier];

```
    UIView *drawerView = [[UIView alloc] initWithFrame:cell.frame];

    // dark_dotted.png obtained from http://subtlepatterns.com/dark-dot/
    // Made by Tsvetelin Nikolov http://dribbble.com/bscsystem
    drawerView.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"dark_dotted"]];

    cell.drawerView = drawerView;       
}
```

**Comment by gloubibou** [comment]
Please try setting a cell class or prototype cell of HHPanningTableViewCell

Also try using the more modern - (id)dequeueReusableCellWithIdentifier:(NSString *)identifier forIndexPath:(NSIndexPath *)indexPath API

**Comment by vburojevic** [comment]
Cell is set to HHPanningTableViewCell class, (id)
dequeueReusableCellWithIdentifier:(NSString *)identifier
forIndexPath:(NSIndexPath *)indexPath not working

**Comment by gloubibou** [comment]
Please try the test code created for issue #6.
This uses storyboard and auto-layout.

https://dl.dropbox.com/u/2381634/GitHub/TestStoryboardHHPanning.zip

**Comment by vburojevic** [comment]
I tried it, it does not use prototype cells, it just uses storyboard with
UITableView, but cells are created the same way.

I tried to add the code in -(void)awakeFromNib method, it works now, but
cells are reused, so if I pan one cell and scroll down, some of the cells
will be revealed too.

Any ideas on how to fix this Pierre?

**Comment by gloubibou** [comment]
Sorry. I missed that bit in your original post.

With prototype cells, the dequeued cell will indeed never be nil.
So you will need to find another place to add the drawer view and background color.

Cell reuse should not be a problem, line 134 of HHPanningTableViewCell.m takes care of closing the drawer on reuse.

Can you create a sample project which exhibits a problem with cell reuse?

**Comment by vburojevic** [comment]
In HHPanningTableViewCell, I have replaced awakeFromNib method with this one:
- (void)awakeFromNib
  {
  UIView *drawerView = [[UIView alloc] initWithFrame:self.frame];
  
  drawerView.backgroundColor = [UIColor blueColor];
  
  self.drawerView = drawerView;
  
  self.directionMask = 2;
  }

Test project:
http://d.pr/f/vn78

**Comment by gloubibou** [comment]
Sounds like a good solution. awakeFromNib should only be called when using prototype cells.

**Comment by vburojevic** [comment]
Yes, but the problem persists, did you check the test project?

**Comment by gloubibou** [comment]
Just had a look at the test project.
- You should use dequeueReusableCellWithIdentifier:forIndexPath:
- Cloning the prototype cell call into initWithCoder:. You can complete initialization here
- You could also try setting the drawerView IBOutlet in Interface builder. If that works, it would be a cleaner solution

**Comment by vburojevic** [comment]
Ok, thank you!
