### ISSUE TITLE
Cocoapods broken

### ISSUE THREAD

**Issue by yakubbaev** [gloubibou/HHPanningTableViewCell#20]
When installing with
pod 'HHPanningTableViewCell'
It includes AppDelegate.\* files and causes linker errors.
I assume cocoapods master repo should be updated with .podspec from this repo.

**Comment by gloubibou** [comment]
Will submit 2.0.0 to CocoaPods

**Comment by georgemp** [comment]
Hi,
  Any idea when 2.0.0 will be available in CocoaPods? Thanks

**Comment by gloubibou** [comment]
Soon. Sorry, I had forgotten about the CocoaPods submission
