### ISSUE TITLE
Cell crashing

### ISSUE THREAD

**Issue by aashish-a10** [gloubibou/HHPanningTableViewCell#23]
![screen shot 2013-09-25 at 6 27 15 pm](https://f.cloud.github.com/assets/1210063/1209123/1a83041c-25e2-11e3-9cef-3ed4fe204608.png)
[containerView insertSubview:subview atIndex:0]; on line 617 causing crash in IOS 7

**Comment by gloubibou** [comment]
iOS 7 will require major changes in HHPanningTableViewCell

I have started work on those, but the update is not yet ready.
You can get the current version of the code at:
https://dl.dropboxusercontent.com/u/2381634/GitHub/HHPanningTableViewCell-iOS7.zip

Revealing cells should work. Swiping to close does not yet work.

**Comment by gloubibou** [comment]
Fixed by commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35
