### ISSUE TITLE
Additional box shown on panning after rotation

### ISSUE THREAD

**Issue by georgemp** [gloubibou/HHPanningTableViewCell#24]
If I do the following, an extra box is seen in the drawer view
1. Pan to show drawer view
2. Close drawer view
3. Rotate device
4. Pan to show drawer view

The box is more prominently seen with tableView cell's that are taller than the default. Is there a way to avoid this? Thanks

Screenshot from the demo app is attached

![hhpanningtableviewcell after rotation](https://f.cloud.github.com/assets/1289458/1459208/e2c0cd3a-43c7-11e3-93dc-862a20486409.png)

**Comment by gloubibou** [comment]
This is the shadowView.
It seems like it is not positioned correctly after the table row width changed.

Please try adding these two lines at line #552:

```
CGRect  shadowFrame = CGRectInset([self bounds], HH_PANNING_SHADOW_INSET, 0.0f);

[shadowView setFrame:shadowFrame];
```

**Comment by georgemp** [comment]
That seems to fix it. I can't get the shadow view (extra box) to show after adding those two lines
