### ISSUE TITLE
I tried to swipe to reaveal back view, it performs the segue instead

### ISSUE THREAD

**Issue by andykimisgreat** [gloubibou/HHPanningTableViewCell#29]
I noticed in your example project, the didSelectRow, you just deselect row. But in my project, the cell perform a segue. How to make it when I am scrolling, it should not perform the segue, it should reveal the back view instead?

**Comment by gloubibou** [comment]
I don't know much about segues. I guess this should help: http://stackoverflow.com/questions/9248798/perform-segue-programmatically-and-pass-parameters-to-the-destination-view
