### ISSUE TITLE
Using with a CustomCell with AutoLayout

### ISSUE THREAD

**Issue by GaetanJuvin** [gloubibou/HHPanningTableViewCell#3]
I tried to implement a custom tableviewcell by inheriting HHPanningTableViewCell I met two bugs:
- The pan gesture label seems not working
- And the second, at the launch of the application, click directly on a TableCell to change views. Go back and try to swipe on a cell.. labels disappear.

Test on IOS6 with a storyboard. An empty project with the 2 bugs: http://www.filedropper.com/test_9

**Comment by gloubibou** [comment]
Both issues were triggered by the use of AutoLayout.

I could fix the first issue by preventing layoutSubviews during panning.

The second issue is caused by your AutoLayout constraints being relative to the cell. I believe they should be relative to the content view.
