### ISSUE TITLE
HHCell not disposing 

### ISSUE THREAD

**Issue by SeanDunford** [gloubibou/HHPanningTableViewCell#31]
When I call     

```
[tableView deleteRowsAtIndexPaths:array withRowAnimation:UITableViewRowAnimationLeft];
```

I get a box of the HHInnerShadow overlay on my tableview. It only sticks out a little. I imagine as much as the offset (inset) of the drop shadow is. When I look at the UI in reveal (revealapp.com), I see that the tableview part has been disposed, but the HHViews are all still retained. Any suggestions?

**Comment by SeanDunford** [comment]
For now I am just setting the tableViewCell inset like this 

```
#define HH_PANNING_SHADOW_INSET         0.0f
```

but those cells that I am Deleting are never getting reused even after tableview updates and are stacking up off screen. For now it isn't an issue but could cause some performance hinderance under different circumstances. Anyone have any idea on how to get 

```
[tableView deleteRowsAtIndexPaths:array withRowAnimation:UITableViewRowAnimationLeft];
```

to actually dispose of a cell of type HHPanningTableViewCell

**Comment by davidmcraejr** [comment]
Sean this might solve your issue also-

Add to dealloc in HHPanningTableViewCell -

UIView  *superview  = self.superview;

UIView  *drawerView = self.drawerView;
UIView  *shadowView = self.shadowView;

if (shadowView) {
    [drawerView removeFromSuperview];
    [shadowView removeFromSuperview];
}
else {
    [drawerView removeFromSuperview];
}

[superview setNeedsDisplay];

**Comment by davidmcraejr** [comment]
Update see issue 33 to for a poll request that solved this for us
