### ISSUE TITLE
Swiping twice in the open direction hides draw and original cell

### ISSUE THREAD

**Issue by fewstera** [gloubibou/HHPanningTableViewCell#37]
When swiping the direction of the reveal twice, the cell turns blank.

This is present within the demo application.

Currently building for iOS 7.1.

![screen shot 2014-06-20 at 00 00 26](https://cloud.githubusercontent.com/assets/1465605/3334786/906572d2-f805-11e3-953e-413da5694cf4.png)

**Comment by gloubibou** [comment]
Seems this bug was introduced by  the previous commit.
The latest version should fix the original issue without causing the views to be removed.

**Comment by fewstera** [comment]
Thank you very much for this fix and the entire project.
