### ISSUE TITLE
Layout problem with accessoryType and self.accessoryView

### ISSUE THREAD

**Issue by Bejil** [gloubibou/HHPanningTableViewCell#5]
When subclassing an existing tableViewCell with HHPanningTableViewCell, accessoryType and accessoryView disappear. Then drawerView display a white stripe on the right corresponding to the width of accessoryView.

![Capture d e cran 2012-12-17 a 15 38 48](https://f.cloud.github.com/assets/1590684/16852/9aa9e098-4857-11e2-8932-187296573bc1.png)

**Comment by gloubibou** [comment]
Can you post a sample application showing the problem?
Are you using auto-layout for your table cell? HHPanningTableViewCell doesn't quite like that.

HHPanningTableViewCell animations work by getting all of the content view subviews and moving them to a container view which can slide horizontally. Maybe this process failed to grab the accessory view.

**Comment by Bejil** [comment]
Here is an example based on your project:
https://dl.dropbox.com/u/28875795/HHPanningTableViewCell-master.zip

**Comment by Bejil** [comment]
I don't set any autoresizing mask for my cell.
I just noticed that the accessory disappear from the cell in default state too :(

**Comment by gloubibou** [comment]
Please try replacing -[HHPanningTableViewCell layoutSubviews] with this implementation:

``` objective-c
- (void)layoutSubviews
{
    [super layoutSubviews];

    if (self.isPanning) {
        return;
    }

    UIView* cellView = self;
    UIView* containerView = self.containerView;
    UIView* drawerView = self.drawerView;
    UIView* shadowView = self.shadowView;
    UIView* backgroundView = self.backgroundView;
    UIView* contentView = self.contentView;

    if (!self.animationInProgress) {
        CGRect cellBounds = [cellView bounds];
        CGRect containerFrame = [containerView frame];

        containerFrame.size.height = cellBounds.size.height;
        containerFrame.size.width = cellBounds.size.width;

        if (self.drawerRevealed) {
            if (containerFrame.origin.x > cellBounds.origin.x) {
                containerFrame.origin.x = cellBounds.origin.x + cellBounds.size.width;
            }
            else {
                containerFrame.origin.x = cellBounds.origin.x - cellBounds.size.width;
            }

            [containerView setFrame:containerFrame];

            [containerView addSubview:backgroundView];
            [containerView addSubview:contentView];

            [self insertSubview:drawerView belowSubview:containerView];
            [self insertSubview:shadowView aboveSubview:drawerView];
        }
        else {
            [containerView setFrame:containerFrame];
            [containerView addSubview:backgroundView];
            [containerView addSubview:contentView];

            [self addSubview:containerView];
        }
    }

    // Move other subviews. E.g. drag reorder control
    for (UIView *subview in [self.subviews reverseObjectEnumerator]) {
        if (subview == containerView) {
            continue;
        }

        if (subview == drawerView) {
            continue;
        }

        if (subview == shadowView) {
            continue;
        }

        if (subview == backgroundView) {
            continue;
        }

        if (subview == contentView) {
            continue;
        }

        [containerView insertSubview:subview atIndex:0];
    }

    [drawerView setFrame:[cellView bounds]];

    [self updateShadowFrame];
}
```

**Comment by Bejil** [comment]
Great, this is working ! Thanks !
But the default state of cells still doesn't show the accessoryView :p

**Comment by gloubibou** [comment]
Not quite sure what you mean.

Your project lacks a disclosureIndicator.png image file.

**Comment by Bejil** [comment]
My real project don't ;) Here's the image if you want to try. Thanks
![disclosureIndicator](https://f.cloud.github.com/assets/1590684/17046/74565eb0-4863-11e2-8757-dcc7902e5b7e.png)
![disclosureIndicator 2x](https://f.cloud.github.com/assets/1590684/17047/7468c60e-4863-11e2-9b3b-93273b34a2d4.png)

**Comment by gloubibou** [comment]
The accessory views show fine here.

I have uploaded an updated copy of your sample project:
https://dl.dropbox.com/u/2381634/GitHub/HHPanningTableViewCell-master.zip

**Comment by Bejil** [comment]
Ok you're right. The issue must be in my project, I'll check.
Thanks anyway !

**Comment by Bejil** [comment]
Ok I fix my problem. Setting the cell's backgroundView (cell.backgroundView or self.backgroundView) will make the accessory hidden. I'm trying to fix this...

**Comment by gloubibou** [comment]
Have a look at layoutSubviews. I wonder if the accessoryView might end up behind the backgroundView after both are moved to the containerView.

**Comment by Bejil** [comment]
Yep thanks now it's working with theese changes :

```
- (void)layoutSubviews
{
    [super layoutSubviews];

    if (self.isPanning) {
        return;
    }

    UIView* cellView = self;
    UIView* containerView = self.containerView;
    UIView* drawerView = self.drawerView;
    UIView* shadowView = self.shadowView;
    UIView* backgroundView = self.backgroundView;
    UIView* contentView = self.contentView;
    **UIView* accessoryView = self.accessoryView;**

    if (!self.animationInProgress) {
        CGRect cellBounds = [cellView bounds];
        CGRect containerFrame = [containerView frame];

        containerFrame.size.height = cellBounds.size.height;
        containerFrame.size.width = cellBounds.size.width;

        if (self.drawerRevealed) {
            if (containerFrame.origin.x > cellBounds.origin.x) {
                containerFrame.origin.x = cellBounds.origin.x + cellBounds.size.width;
            }
            else {
                containerFrame.origin.x = cellBounds.origin.x - cellBounds.size.width;
            }

            [containerView setFrame:containerFrame];

            [containerView addSubview:backgroundView];
            [containerView addSubview:accessoryView];
            [containerView addSubview:contentView];

            [self insertSubview:drawerView belowSubview:containerView];
            [self insertSubview:shadowView aboveSubview:drawerView];
        }
        else {
            [containerView setFrame:containerFrame];
            [containerView addSubview:backgroundView];
            [containerView addSubview:accessoryView];
            [containerView addSubview:contentView];

            [self addSubview:containerView];
        }
    }

    // Move other subviews. E.g. drag reorder control
    for (UIView *subview in [self.subviews reverseObjectEnumerator]) {
        if (subview == containerView) {
            continue;
        }

        if (subview == drawerView) {
            continue;
        }

        if (subview == shadowView) {
            continue;
        }

        if (subview == backgroundView) {
            continue;
        }

        if (subview == accessoryView) {
            continue;
        }

        if (subview == contentView) {
            continue;
        }

        [containerView insertSubview:subview atIndex:0];
    }

    [drawerView setFrame:[cellView bounds]];

    [self updateShadowFrame];
}
```

**Comment by MihirPatel1990** [comment]
in This api now not working in Xcode 5.0 
i mean not compitable with iOS 7

**Comment by MihirPatel1990** [comment]
in This api now not working in Xcode 5.0 
i mean not compatible with iOS 7

**Comment by MihirPatel1990** [comment]
Please help me

**Comment by gloubibou** [comment]
iOS 7 will require major changes in HHPanningTableViewCell

I have started work on those, but the update is not yet ready.
You can get the current version of the code at:
https://dl.dropboxusercontent.com/u/2381634/GitHub/HHPanningTableViewCell-iOS7.zip

Revealing cells should work. Swiping to close does not yet work.

**Comment by MihirPatel1990** [comment]
ok
Thanks..!!

if it is possible to reminder me on livebirdtech@gmail.com than plz send me

**Comment by MihirPatel1990** [comment]
any Update??

**Comment by gloubibou** [comment]
Fixed with commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35

**Comment by MihirPatel1990** [comment]
Stil Some Problem when reload cell

**Comment by gloubibou** [comment]
Do you still have the accessoryView missing?
The link to the sample project is no longer working.

**Comment by MihirPatel1990** [comment]
the problem is...when i reload the cell the content view get hides....and only the drawer view is there...
Any idea why its happening ?

**Comment by MihirPatel1990** [comment]
any Help?

**Comment by gloubibou** [comment]
I have tried and failed  to reproduce the problem with this code:
    double delayInSeconds = 2.0;
    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds \* NSEC_PER_SEC));
    dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
        [self.tableView reloadRowsAtIndexPaths:@[ [NSIndexPath indexPathForRow:1 inSection:0] ] withRowAnimation:UITableViewRowAnimationNone];
    });

**Comment by JaimeYesidLeonParada** [comment]
The version for iOS work fine; thanks man.
