### ISSUE TITLE
Storyboard Cells & autolayout example

### ISSUE THREAD

**Issue by ghost** [gloubibou/HHPanningTableViewCell#6]
is there any example about how to implement it with custom cells in storyboard  ? Already did it via code but couldn't succeed in storyboard.  Objects in the contentView of the cell disappear after swiping and become not visible anymore except during the swipe reveal.

**Comment by gloubibou** [comment]
I have never actually used storyboards.

Could you create a sample project?

**Comment by prdlk** [comment]
I have the same issue has anyone looked into this?

**Comment by gloubibou** [comment]
Is the problem triggered by storyboards or by auto layout?

Could you create a sample project?

**Comment by prdlk** [comment]
https://github.com/prnk28/TestStoryboardHHPanning 

here you go a test/sample project!!

**Comment by gloubibou** [comment]
I fixed the sample project: https://dl.dropbox.com/u/2381634/GitHub/TestStoryboardHHPanning.zip

**Comment by prdlk** [comment]
THANK YOU!

**Comment by prdlk** [comment]
can you post what you did with a commit?

**Comment by prdlk** [comment]
did you not use the xib and create the table programmitically?

**Comment by gloubibou** [comment]
- I have added many files to the actual target being run. Many were only in the test target
- I have overloaded the designated initializer for UITableViewController
- The table view is created in the storyboard nib
- FileMerge should show you the other differences

**Comment by prdlk** [comment]
I tried to implement what you have done in the sample project into my actual project: ( https://github.com/prnk28/FloadtTest)
however nothing is loading??? could you please assist me?

**Comment by gloubibou** [comment]
http://screencast.com/t/rkph670Vy

**Comment by prdlk** [comment]
wow I feel stupid...
