### ISSUE TITLE
Add property to change HH_PANNING_MINIMUM_PAN?

### ISSUE THREAD

**Issue by jklp** [gloubibou/HHPanningTableViewCell#7]
Hi, first I'd like to say thanks for the great library!  

I've been using it a bit in my latest project, though in this project I need to set the minimum pan distance for revealing the drawer.  

I've updated the class on my local machine so you can set the minimum pan via a property (instead of the variable being a #define).   Did you want me to send you a pull request for this?  

Thanks
Jerrold

**Comment by gloubibou** [comment]
Hi,

Yes please do send a pull request.

Please let me know which product you are using HHPanningTableViewCell in. Once you are ready to disclose that information.

Pierre

**Comment by jklp** [comment]
Thanks, see https://github.com/gloubibou/HHPanningTableViewCell/pull/8 for the pull request.  

The app that I'm using it for is called Flip Messenger, a mobile messenger that I wrote.  Version 2.0 is still in development (and should be out in the next couple of weeks), though you can see the current version at http://flipmessenger.com/  

Thanks
Jerrold
